// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  post_cards: dynamic(() => import("./PostCards")),
  rich_text: dynamic(() => import("./RichText")),
};
